name: Publish to Maven

on:
  release:
    types: [ created ]

jobs:
  linux-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build everything
        run: ./gradlew build

      - name: Publish to GitHub Packages
        run: ./gradlew publishKotlinMultiplatformPublicationToMavenRepository publishJvmPublicationToMavenRepository publishJsPublicationToMavenRepository publishLinuxX64PublicationToMavenRepository publishMavenPublicationToMavenRepository
        env:
          GHP_USERNAME: ${{ github.actor }}
          GHP_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos-publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build everything
        run: ./gradlew build

      - name: Publish to GitHub Packages
        run: ./gradlew publishMacosX64PublicationToMavenRepository
        env:
          GHP_USERNAME: ${{ github.actor }}
          GHP_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows-publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build everything
        run: ./gradlew build

      - name: Publish to GitHub Packages
        run: ./gradlew publishMingwX64PublicationToMavenRepository
        env:
          GHP_USERNAME: ${{ github.actor }}
          GHP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
