name: Gradle Test

on:
  workflow_dispatch:
  push:
    branches:
    - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: '11'

    - name: JVM Tests
      run: ./gradlew mastodonk-core:jvmTest

    - name: JS Tests
      run: ./gradlew mastodonk-core:jsTest

    - name: Native Tests
      run: ./gradlew mastodonk-core:nativeTest
