name: JS Build

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Core JS Tests
        run: ./gradlew mastodonk-core:jsTest
