name: JVM Build

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build-jvm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Core JVM Tests
        run: ./gradlew mastodonk-core:jvmTest

      - name: Paging JVM Tests
        run: ./gradlew mastodonk-paging:jvmTest

      - name: Sample JVM Build
        run: ./gradlew sample-jvm:build
